import React,{useEffect,useState} from 'react';
import {Routes,Route,Link,useNavigate} from 'react-router-dom';
import {products,search,login,register,createOrder,orders} from './services/api';

function Header({cartCount}) {
 const [q,setQ]=useState(''); const nav=useNavigate();
 const submit=e=>{e.preventDefault();nav('/search?q='+encodeURIComponent(q));};
 return <header><Link className="brand" to="/">VAM Collections</Link>
 <form onSubmit={submit} className="search"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search products"/><button>Search</button></form>
 <nav><Link to="/login">Login</Link><Link to="/orders">Orders</Link><Link to="/cart">🛒 {cartCount}</Link></nav></header>
}
function Home({add}){const [items,setItems]=useState([]);useEffect(()=>products().then(r=>setItems(r.data)),[]);return <><section className="hero"><h1>Welcome to VAM Collections</h1><p>Everything you need, all in one place.</p></section><h2>Featured Products</h2><div className="grid">{items.map(p=><Card key={p.id} p={p} add={add}/>)}</div></>}
function Card({p,add}){return <article className="card"><img src={p.imageUrl}/><h3>{p.name}</h3><p>{p.description}</p><strong>₹{p.price.toLocaleString()}</strong><button onClick={()=>add(p)}>Add to Cart</button></article>}
function SearchPage({add}){const params=new URLSearchParams(location.search);const [items,setItems]=useState([]);useEffect(()=>search(params.get('q')||'').then(r=>setItems(r.data)),[]);return <><h2>Search Results</h2><div className="grid">{items.map(p=><Card key={p.id} p={p} add={add}/>)}</div></>}
function LoginPage({setUser}){const [email,setEmail]=useState(''),[password,setPassword]=useState('');const nav=useNavigate();const submit=async e=>{e.preventDefault();try{const r=await login({email,password});localStorage.setItem('user',JSON.stringify(r.data));setUser(r.data);nav('/');}catch{alert('Invalid email or password')}};return <Form title="Login" onSubmit={submit}><input placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} required/><button>Login</button><p>New customer? <Link to="/register">Create account</Link></p></Form>}
function Register(){const [data,setData]=useState({name:'',email:'',password:'',address:'',phone:''});const nav=useNavigate();const submit=async e=>{e.preventDefault();await register(data);alert('Registration successful');nav('/login')};return <Form title="Create Account" onSubmit={submit}>{['name','email','password','address','phone'].map(k=><input key={k} type={k==='password'?'password':'text'} placeholder={k[0].toUpperCase()+k.slice(1)} value={data[k]} onChange={e=>setData({...data,[k]:e.target.value})} required/>)}<button>Create Account</button></Form>}
function Form({title,onSubmit,children}){return <form className="form" onSubmit={onSubmit}><h2>{title}</h2>{children}</form>}
function Cart({items,remove,checkout}){return <><h2>Your Cart</h2>{!items.length?<p>Your cart is empty.</p>:<div className="cart">{items.map((p,i)=><div className="cartrow" key={p.id}><img src={p.imageUrl}/><span>{p.name}</span><b>₹{p.price}</b><button onClick={()=>remove(i)}>Remove</button></div>)}<h3>Total: ₹{items.reduce((s,p)=>s+p.price,0).toLocaleString()}</h3><button onClick={checkout}>Place Order</button></div>}</>}
function Orders(){const [list,setList]=useState([]);useEffect(()=>{const u=JSON.parse(localStorage.getItem('user'));if(u)orders(u.id).then(r=>setList(r.data))},[]);return <><h2>My Orders</h2>{list.map(o=><div className="order" key={o.id}><b>Order #{o.id}</b><span>₹{o.totalAmount}</span><span>{o.status}</span></div>)}</>}
export default function App(){const [user,setUser]=useState(()=>JSON.parse(localStorage.getItem('user')||'null'));const [cart,setCart]=useState(()=>JSON.parse(localStorage.getItem('cart')||'[]'));useEffect(()=>localStorage.setItem('cart',JSON.stringify(cart)),[cart]);const add=p=>setCart(c=>c.some(x=>x.id===p.id)?c:[...c,p]);const remove=i=>setCart(c=>c.filter((_,x)=>x!==i));const checkout=async()=>{if(!user){alert('Please login first');return}const total=cart.reduce((s,p)=>s+p.price,0);await createOrder({userId:user.id,totalAmount:total});setCart([]);alert('Order placed successfully')};return <><Header cartCount={cart.length}/><main><Routes><Route path="/" element={<Home add={add}/>}/><Route path="/search" element={<SearchPage add={add}/>}/><Route path="/login" element={<LoginPage setUser={setUser}/>}/><Route path="/register" element={<Register/>}/><Route path="/cart" element={<Cart items={cart} remove={remove} checkout={checkout}/>}/><Route path="/orders" element={<Orders/>}/></Routes></main><footer>© VAM Collections</footer></>}
